<!DOCTYPE html>
<html>
	<head>
		<title>Beer Please</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />

		<link rel="shortcut icon" href="/icon.png">
		<link rel="apple-touch-icon" href="/icon.png" />
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

		<meta property="og:image" content="/icon.png">
		<meta property="og:title" content="Beer Squirrel">
		<meta property="og:url" content="http://beersquirrel.xyz">
		<meta property="og:site_name" content="Beer Squirrel">

		<link href="/style.css" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Coustard:400,900' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.min.css" />
	</head>
	<body>
		<div class="github-fork-ribbon-wrapper right">
			<div class="github-fork-ribbon">
				<a href="https://github.com/arzynik/beerplease">Fork me on GitHub</a>
			</div>
		</div>

		<div class="chunk buy-text">
			<div class="buy-text-buy">Send&nbsp;<span class="owner-first-name"></span></div>
			<div class="beer-counter-wrapper">
				<div class="beer-counter"><input type="text" class="beer-input chunk" value="1"></div>
			</div>
			<div class="buy-text-beer"><span class="buy-text-beer-text">beer</span>.<span class="star">*</span></div>

			<button class="buy-button chunk" id="customButton">send <span class="buy-button-it">it</span>!</button>

			<div class="beer-text-star">* Not actually beer or any form of physical good or service. A $5 per quantity donation.</div>
		</div>

		<div class="beers">
			<div class="beer beer-origional" style="z-index: 500; margin: -15px 0 0 15px;"></div>
		</div>

		<div class="beer-slider-wrapper">
			<div class="beer-slider"></div>
			<div class="beer-slider-endcap"></div>
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://checkout.stripe.com/checkout.js"></script>
		<script type="text/javascript" src="/fastclick.js"></script>
		<script type="text/javascript" src="/script.js"></script>
	</body>
</html>
