<!DOCTYPE html>
<html ng-app="BeerPlease">
	<head>
		<title><?=$config['general']['title']?></title>
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, shrink-to-fit=no" />

		<base href="/">

		<link rel="shortcut icon" href="/icon.png">
		<link rel="apple-touch-icon" href="/icon.png" />

		<meta property="og:image" content="/icon.png">
		<meta property="og:title" content="Beer Please!">
		<meta property="og:url" content="<?=$_SERVER['HTTP_HOST']?>">
		<meta property="og:site_name" content="Beer Please!">

		<link href="/style.css" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="content">
			<h1><?=$config['general']['title']?></h1>

			<div class="tagline">
				<h2>Send <?=$config['general']['name']?></h2>
				<div class="beer-counter"><input type="text" class="beer-input" value="1" ng-model="beers"></div>
				<h2>ice cream{{beers > 1 ? 's' : ''}}*</h2>
			</div>

			<div class="slider">
				<input type="range" id="range" value="1" max="99" min="1" ng-model="beers">
			</div>

			<div class="button">
				<button ng-click="pay()">send {{beers > 1 ? '\'em' : 'it'}}!</button>
			</div>

			<div class="beers">

				<div class="beer beer-origional"></div>

			</div>

			<div class="footer">
				* Not really ice cream. Just a $5 per quantity payment.
				<br>Created with <a href="http://github.com/arzynik/beerplease" target="_blank">Beer Please</a>, an opensource payment project powered by <a href="http://tipsy.la" target="_blank">Tipsy</a>.
				Made with ♥ by <a href="http://devin.la" target="_blank">Devin</a>.

			</div>
		</div>

		<script>
			var config = {
				stripe: {
					publish: '<?=$config['stripe']['publish']?>',
					bitcoin: <?=$config['stripe']['bitcoin'] ? 'true' : 'false'?>,
					image: '<?=str_replace("'","\\'",$config['stripe']['image'])?>'
				},
				general: {
					name: '<?=str_replace("'","\\'",$config['general']['name'])?>',
					title: '<?=str_replace("'","\\'",$config['general']['title'])?>'

				}
			};
		</script>


		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.2/angular.min.js"></script>
		<script src="https://checkout.stripe.com/checkout.js"></script>
		<script type="text/javascript" src="/fastclick.js"></script>
		<script type="text/javascript" src="/script.js"></script>
	</body>
</html>
